job/job/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('user/', include('user.urls')),
    path('vacancy/', include('vacancy.urls')),
]

job/user/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import EmployerRegisterView, CompanyRegisterView

app_name = 'user'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register_employer/', EmployerRegisterView.as_view(), name='register_employer'),
    path('register_company/', CompanyRegisterView.as_view(), name='register_company'),


]

job/vacancy/urls.py
from django.urls import path
from .views import VacancyListView, CreateVacancyView, CreateResumeView,ResumeListView

app_name = 'vacancy'

urlpatterns = [
    path('vacancy_list/', VacancyListView.as_view(), name='vacancy_list'),
    path('create_vacancy/', CreateVacancyView.as_view(), name='create_vacancy'),
    path('create_resume/', CreateResumeView.as_view(), name='create_resume'),
    path('resume_list/', ResumeListView.as_view(), name='resume_list'),
]

job/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    email = models.EmailField(_('email address'),
                              unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserEmployer(User):
    name = models.CharField(max_length=20, verbose_name='Employer name')


class UserCompany(User):
    company = models.CharField(max_length=30, verbose_name='Company name', blank=True)
    name = models.CharField(max_length=20, verbose_name='Use name if you are not company', blank=True)

job/vacancy/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class ResumeEmployers(models.Model):
    title = models.CharField(max_length=20, verbose_name='title of your resume')
    first_name = models.CharField(max_length=20, verbose_name='Your first name')
    last_name = models.CharField(max_length=20, verbose_name='Your last name')
    resume = models.TextField(verbose_name='Your resume')
    comment = models.TextField(verbose_name='Information', blank=True)
    phone = PhoneNumberField(unique=True, blank=False, null=False, verbose_name='Your number phone')
    email = models.EmailField(unique=True, null=False, blank=False, verbose_name='Your email')

    def __str__(self):
        return self.title


class VacancyCompany(models.Model):
    title = models.CharField(max_length=20, verbose_name='title of your vacancy')

    first_name = models.CharField(max_length=20, verbose_name='Your first name')
    last_name = models.CharField(max_length=20, verbose_name='Your last name')
    vacancy = models.TextField(verbose_name='Your vacancy')
    comment = models.TextField(verbose_name='Information', blank=True)
    phone = PhoneNumberField(unique=True, blank=False, null=False, verbose_name='Your number phone')
    email = models.EmailField(unique=True, null=False, blank=False, verbose_name='Your email')

    def __str__(self):
        return self.title

job/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from .models import UserEmployer, UserCompany


# User = get_user_model()


class EmployerCreationForm(UserCreationForm):
    email = forms.EmailField(label=_("Email"), max_length=254, )

    class Meta(UserCreationForm.Meta):
        model = UserEmployer
        fields = ("email", "username", "name",)


class CompanyCreationForm(UserCreationForm):
    email = forms.EmailField(label=_("Email"), max_length=254, )

    class Meta(UserCreationForm.Meta):
        model = UserCompany
        fields = ("email", "username", "name", "company",)

job/vacancy/forms.py
from django import forms

from .models import VacancyCompany, ResumeEmployers


class VacancyForm(forms.ModelForm):
    class Meta:
        model = VacancyCompany
        fields = ('title', 'first_name', 'last_name', 'phone', 'vacancy', 'comment', 'email')


class ResumeForm(forms.ModelForm):
    class Meta:
        model = ResumeEmployers
        fields = ('title', 'first_name', 'last_name', 'resume', 'comment', 'phone', 'email')

job/user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import EmployerCreationForm, CompanyCreationForm


class EmployerRegisterView(View):
    template_name = 'registration/register_employer.html'

    def get(self, request, *args, **kwargs):
        context = {
            'form': EmployerCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = EmployerCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=password)
            login(request, user)
            gr_job = Group.objects.get(name='Employers')

            user.groups.add(gr_job)
            user.save()
            return redirect('main')
        context = {
            'form': form
        }
        return render(request, template_name='registration/register_employer.html', context=context)


class CompanyRegisterView(View):
    template_name = 'registration/register_company.html'

    def get(self, request, *args, **kwargs):
        context = {
            'form': CompanyCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = CompanyCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=password)
            login(request, user)
            gr_job = Group.objects.get(name='Companies')
            user.groups.add(gr_job)
            user.save()
            return redirect('main')
        context = {
            'form': form
        }
        return render(request, template_name='registration/register_company.html', context=context)

job/vacancy/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, View
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404
from .models import VacancyCompany, ResumeEmployers
from .forms import VacancyForm, ResumeForm


# Create your views here.
class VacancyListView(ListView):
    template_name = 'vacancy_list.html'
    model = VacancyCompany
    context_object_name = 'vacancy'


class CreateVacancyView(PermissionRequiredMixin, View):
    template_name = 'create_vacancy.html'

    def get(self, request, *args, **kwargs):
        context = {
            'form': VacancyForm()
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = VacancyForm(request.POST)
        if form.is_valid():
            form.save()
        context = {
            'form': form
        }
        return render(request, template_name='create_vacancy.html', context=context)

    def has_permission(self):
        if self.request.user.groups.filter(name='Companies').exists():
            return True


# class CreateVacancyView(PermissionRequiredMixin, CreateView):
#     groups = Group.objects.filter(name='Companies')
#     print(groups)
#
#     template_name = 'create_vacancy.html'
#     success_url = '/'
#     form_class = VacancyForm
#

# def has_permission(self):
#     if not self.request.user.groups.filter(name='Companies').exists():
#         raise Http404


class ResumeListView(ListView):
    template_name = 'resume_list.html'
    model = ResumeEmployers
    context_object_name = 'resume'


class CreateResumeView(CreateView):
    template_name = 'create_resume.html'
    success_url = '/'
    form_class = ResumeForm

job/user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Find job</title>
</head>
<body class="container">
 {% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<ul class="align-content-sm-around">
    <li class="list-group-item">
        User: {{ user }}
    </li>
    <li class="list-group-item">
        <a href="{% url 'main' %}">Home</a>
    </li>
</ul>
{% block content %}
{% endblock %}
</body>
</html>

job/user/templates/main.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<body>
  <hr>
{% if user.is_authenticated %}
  <a href="{% url 'user:logout' %}">Logout</a>
  <h3>Vacancy</h3>
  <p class="list-group"><a href="{% url 'vacancy:vacancy_list'%}">All vacancy</a></p>
  <p class="list-group"> <a href="{% url 'vacancy:create_vacancy' %}">Add new vacancy</a> </p>
  <h3>Resume</h3>
  <p><a href="{% url 'vacancy:resume_list' %}">All resume</a></p>
  <p><a href="{% url 'vacancy:create_resume'%}">Add new resume</a></p>
{% else %}
  <a href="{% url 'user:login' %}">LogIn</a>  |
  <h3>Looking for job?</h3>
  <a href="{% url 'user:register_employer' %}">Enter here</a>
  <h3>Looking for employers? </h3>
  <a href="{% url 'user:register_company' %}">Enter here</a>
{% endif %}

</body>
{% endblock %}

job/vacancy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Find job</title>
</head>
<body class="container">
 {% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<ul class="align-content-sm-around">
    <li class="list-group-item">
        User: {{ user }}
    </li>
    <li class="list-group-item">
        <a href="{% url 'user:main' %}">Home</a>
    </li>
</ul>
{% block content %}
{% endblock %}
</body>
</html>

job/vacancy/templates/create_resume.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<h3>Create new resume</h3>
<form  method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}

job/vacancy/templates/create_vacancy.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<h3>Create new vacancy</h3>
<form  method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}

job/vacancy/templates/resume_list.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<h3>All resume </h3>
{% if resume %}
{% for elem in resume %}
{{ elem }}
{{ elem.pk }}
{% endfor %}
{% else %}
<p class="list-group"> page is empty </p>
{% endif %}

{% endblock %}

job/vacancy/templates/vacancy_list.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<h3>All vacancy</h3>
{% if vacancy %}
{% for elem in vacancy %}
{{ elem }}
{{ elem.pk }}
{% endfor %}
{% else %}
<p class="list-group"> page is empty </p>
{% endif %}

{% endblock %}